export const excludedData = [
  'defense-mechanism',
  'thoma',
  'traveler-geo',
  'traveler-electro',
  'traveler-anemo',
  'raiden',
  'ayaka',
  'sara',
  'kokomi',
  'kazuha',
  'akuoumaru',
  'calamity-queller',
  'cinnabar -spindle',
  'eberlasting-moonglow',
  'haran-geppaku-futsu',
  "kagura's-verity",
  "mouun's-moon",
  'oathsworn-eye',
  'polar-star',
  'prototype-archaic',
  'predator',
  'redhorn-stonethresher',
  'royal-spear',
  "wavebreaker's-fin",
  'alley-hunter',
]
